package com.alan.testproject.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.alan.testproject.bean.ResponseBean;

import com.alan.testproject.dao.ResponseBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig responseBeanDaoConfig;

    private final ResponseBeanDao responseBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        responseBeanDaoConfig = daoConfigMap.get(ResponseBeanDao.class).clone();
        responseBeanDaoConfig.initIdentityScope(type);

        responseBeanDao = new ResponseBeanDao(responseBeanDaoConfig, this);

        registerDao(ResponseBean.class, responseBeanDao);
    }
    
    public void clear() {
        responseBeanDaoConfig.clearIdentityScope();
    }

    public ResponseBeanDao getResponseBeanDao() {
        return responseBeanDao;
    }

}
